server:
  port: 9527

#发布到eurake中的微服务的名字
spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true                                 #访问路径可以显示ip地址
#配置zuul路由的映射规则
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: "*"     #忽略所有的服务
  prefix: /shy              #所有的服务前缀